// frontend/src/components/agent/AiAssistant.jsx
import { useState, useEffect, useRef } from 'react';
import { Sparkles, X, Send, Trash2, Bot, User, ArrowDownCircle } from 'lucide-react';
import api from '../../services/api';

export default function AiAssistant({ currentWatchlistId, onWatchlistsChange }) {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState(() => {
    try {
      return JSON.parse(localStorage.getItem('aw_agent_messages')) || [
        {
          role: 'assistant',
          text: "Hello! I'm your AlphaWatch AI Assistant. I can manage your watchlists, write and edit custom scoring scripts, configure price alerts, and run strategy backtests. Try selecting a suggestion below!"
        }
      ];
    } catch {
      return [
        {
          role: 'assistant',
          text: "Hello! I'm your AlphaWatch AI Assistant. I can manage your watchlists, write and edit custom scoring scripts, configure price alerts, and run strategy backtests. Try selecting a suggestion below!"
        }
      ];
    }
  });
  const [inputValue, setInputValue] = useState('');
  const [loading, setLoading] = useState(false);
  
  const messagesEndRef = useRef(null);

  useEffect(() => {
    localStorage.setItem('aw_agent_messages', JSON.stringify(messages));
  }, [messages]);

  useEffect(() => {
    if (isOpen) {
      scrollToBottom();
    }
  }, [messages, isOpen]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const handleSend = async (textToSend) => {
    const text = (textToSend || inputValue).trim();
    if (!text) return;

    if (!textToSend) setInputValue('');

    const userMessage = { role: 'user', text };
    setMessages((prev) => [...prev, userMessage]);
    setLoading(true);

    try {
      const res = await api.post('/agent/chat', {
        message: text,
        currentWatchlistId
      });

      if (res.data?.success) {
        setMessages((prev) => [...prev, { role: 'assistant', text: res.data.response }]);
        if (res.data.refreshRequired) {
          onWatchlistsChange?.();
        }
      } else {
        setMessages((prev) => [...prev, { role: 'assistant', text: 'Error: Could not retrieve response.' }]);
      }
    } catch (err) {
      setMessages((prev) => [
        ...prev,
        { role: 'assistant', text: err.response?.data?.error || 'Failed to connect to the agent service.' }
      ]);
    } finally {
      setLoading(false);
    }
  };

  const clearChat = () => {
    if (window.confirm('Clear conversation history?')) {
      const initial = [
        {
          role: 'assistant',
          text: "Hello! I'm your AlphaWatch AI Assistant. I can manage your watchlists, write and edit custom scoring scripts, configure price alerts, and run strategy backtests. Try selecting a suggestion below!"
        }
      ];
      setMessages(initial);
    }
  };

  // Inline formatting helper
  const renderInlineFormat = (line) => {
    const regex = /(\*\*.*?\*\*|`.*?`)/g;
    const parts = line.split(regex);
    return parts.map((part, idx) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={idx} className="font-extrabold text-slate-100">{part.slice(2, -2)}</strong>;
      }
      if (part.startsWith('`') && part.endsWith('`')) {
        return <code key={idx} className="bg-slate-800 text-indigo-300 font-mono px-1 py-0.5 rounded text-[11px] border border-slate-700/50">{part.slice(1, -1)}</code>;
      }
      return part;
    });
  };

  // Custom table renderer for Markdown tables generated by LLM
  const renderTable = (rows, key) => {
    const parsedRows = rows
      .map(row => row.split('|').map(cell => cell.trim()).filter((_, idx, arr) => idx > 0 && idx < arr.length - 1))
      .filter(row => row.length > 0 && !row.every(cell => cell.startsWith('-')));

    if (parsedRows.length === 0) return null;

    const headers = parsedRows[0];
    const bodyRows = parsedRows.slice(1);

    return (
      <div key={key} className="overflow-x-auto my-2 border border-slate-800 rounded-lg shadow-inner bg-slate-950/40">
        <table className="w-full text-[10px] text-left border-collapse">
          <thead>
            <tr className="bg-slate-900 border-b border-slate-800">
              {headers.map((h, idx) => (
                <th key={idx} className="px-2 py-1.5 font-black uppercase text-slate-300 tracking-wider">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-800/50">
            {bodyRows.map((row, rIdx) => (
              <tr key={rIdx} className="hover:bg-slate-900/30">
                {row.map((cell, cIdx) => {
                  const isProfit = cell.includes('%') && parseFloat(cell) > 0;
                  const isLoss = cell.includes('%') && parseFloat(cell) < 0;
                  const textClass = isProfit ? 'text-emerald-400 font-bold' : isLoss ? 'text-rose-400 font-bold' : 'text-slate-300';
                  return (
                    <td key={cIdx} className={`px-2 py-1.5 font-mono ${textClass}`}>{cell}</td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  };

  // Custom text format processing
  const formatMessageText = (text) => {
    if (!text) return '';
    if (text.includes('|')) {
      const lines = text.split('\n');
      let inTable = false;
      let tableRows = [];
      const elements = [];

      for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        if (line.startsWith('|')) {
          inTable = true;
          tableRows.push(line);
        } else {
          if (inTable && tableRows.length > 0) {
            elements.push(renderTable(tableRows, `table-${i}`));
            tableRows = [];
            inTable = false;
          }
          if (line) {
            elements.push(<p key={i} className="mb-1.5">{renderInlineFormat(line)}</p>);
          }
        }
      }
      if (inTable && tableRows.length > 0) {
        elements.push(renderTable(tableRows, 'table-end'));
      }
      return <div className="space-y-1.5">{elements}</div>;
    }

    return (
      <div className="space-y-1">
        {text.split('\n').map((line, idx) => {
          if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
            return (
              <li key={idx} className="ml-4 list-disc text-xs text-slate-300">
                {renderInlineFormat(line.replace(/^[-*]\s+/, ''))}
              </li>
            );
          }
          return <p key={idx}>{renderInlineFormat(line)}</p>;
        })}
      </div>
    );
  };

  const SUGGESTIONS = [
    "Create a custom score named 'Super trend' adding 50 points if 5m:ema20 crossover 5m:ema50, and assign it to the current watchlist.",
    "Alert me when 5m:close crossunder 5m:sma20 on SBIN stock.",
    "Backtest buying when close > sma50 and selling when close < sma50 on 1d timeframe for the current watchlist.",
    "Add SBIN stock to the current watchlist."
  ];

  return (
    <>
      {/* Floating Action Button */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="fixed bottom-6 right-6 z-40 h-12 w-12 rounded-full flex items-center justify-center cursor-pointer shadow-lg shadow-indigo-600/35 transform hover:scale-105 active:scale-95 transition-all duration-200"
        style={{
          background: 'linear-gradient(135deg, var(--accent) 0%, #4f46e5 100%)',
          border: '1px solid rgba(255,255,255,0.1)'
        }}
        title="AI Trading Assistant"
      >
        {isOpen ? <X size={20} className="text-white" /> : <Sparkles size={20} className="text-white animate-pulse" />}
      </button>

      {/* Floating Chat Container */}
      {isOpen && (
        <div
          className="fixed bottom-20 right-6 z-40 w-[390px] h-[580px] rounded-2xl border flex flex-col overflow-hidden shadow-2xl animate-fade-in"
          style={{
            background: 'rgba(15, 23, 42, 0.85)',
            backdropFilter: 'blur(16px)',
            borderColor: 'var(--border-base)'
          }}
        >
          {/* Header */}
          <header className="px-4 py-3 border-b flex items-center justify-between shrink-0" style={{ borderColor: 'var(--border-base)' }}>
            <div className="flex items-center gap-2">
              <div className="h-6 w-6 rounded-lg bg-indigo-600 flex items-center justify-center">
                <Sparkles size={13} className="text-white" />
              </div>
              <div>
                <h4 className="text-xs font-black uppercase tracking-wider text-slate-100">AlphaWatch AI</h4>
                <p className="text-[9px] text-indigo-400/80 font-bold select-none">Active Agent System Ready</p>
              </div>
            </div>
            <div className="flex items-center gap-1">
              <button
                onClick={clearChat}
                className="p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-slate-200 cursor-pointer transition-colors"
                title="Clear Chat history"
              >
                <Trash2 size={13} />
              </button>
              <button
                onClick={() => setIsOpen(false)}
                className="p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-rose-400 cursor-pointer transition-colors"
              >
                <X size={13} />
              </button>
            </div>
          </header>

          {/* Messages Logs Area */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {messages.map((msg, idx) => (
              <div
                key={idx}
                className={`flex gap-2.5 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}
              >
                {/* Avatar Icon */}
                <div
                  className={`h-7 w-7 rounded-full shrink-0 flex items-center justify-center border text-xs ${
                    msg.role === 'user'
                      ? 'bg-slate-800 border-slate-700 text-slate-300'
                      : 'bg-indigo-950/50 border-indigo-500/20 text-indigo-300'
                  }`}
                >
                  {msg.role === 'user' ? <User size={12} /> : <Bot size={12} />}
                </div>

                {/* Message Bubble */}
                <div
                  className={`rounded-2xl px-3.5 py-2.5 text-[11px] leading-relaxed shadow-sm ${
                    msg.role === 'user'
                      ? 'bg-indigo-600 text-white rounded-tr-none'
                      : 'bg-slate-900 border border-slate-800/80 text-slate-200 rounded-tl-none'
                  }`}
                  style={{ maxWith: msg.role === 'user' ? '75%' : '85%' }}
                >
                  {formatMessageText(msg.text)}
                </div>
              </div>
            ))}

            {/* Pulsing loading state */}
            {loading && (
              <div className="flex gap-2.5">
                <div className="h-7 w-7 rounded-full shrink-0 flex items-center justify-center border bg-indigo-950/50 border-indigo-500/20 text-indigo-300">
                  <Bot size={12} />
                </div>
                <div className="rounded-2xl rounded-tl-none px-4 py-3 bg-slate-900 border border-slate-800 text-slate-400 flex items-center gap-1.5">
                  <span className="h-1.5 w-1.5 rounded-full bg-indigo-500 animate-bounce" style={{ animationDelay: '0ms' }} />
                  <span className="h-1.5 w-1.5 rounded-full bg-indigo-400 animate-bounce" style={{ animationDelay: '150ms' }} />
                  <span className="h-1.5 w-1.5 rounded-full bg-indigo-300 animate-bounce" style={{ animationDelay: '300ms' }} />
                </div>
              </div>
            )}

            <div ref={messagesEndRef} />
          </div>

          {/* Quick Suggestions Chips */}
          {!loading && (
            <div className="px-4 py-2 border-t border-slate-800/40 bg-slate-950/20 shrink-0">
              <span className="text-[8px] font-black uppercase text-indigo-400 block mb-1">Quick Actions</span>
              <div className="flex gap-1.5 overflow-x-auto pb-1 scrollbar-none">
                {SUGGESTIONS.map((sug, i) => (
                  <button
                    key={i}
                    onClick={() => handleSend(sug)}
                    className="whitespace-nowrap px-2.5 py-1.5 bg-slate-900 border border-slate-800 hover:border-indigo-500/40 hover:bg-slate-800/50 rounded-xl text-[9px] font-bold text-slate-400 hover:text-slate-200 cursor-pointer transition-all"
                  >
                    {sug.length > 32 ? sug.slice(0, 30) + '...' : sug}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Text Input Area */}
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSend();
            }}
            className="p-3 border-t flex items-center gap-2 shrink-0 bg-slate-950/40"
            style={{ borderColor: 'var(--border-base)' }}
          >
            <input
              type="text"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              disabled={loading}
              placeholder="Ask AI to backtest, set alerts, customize scores..."
              className="flex-1 border rounded-xl px-3 py-2 text-xs focus:outline-none focus:border-indigo-500/80 disabled:opacity-50"
              style={{
                background: 'var(--bg-base)',
                borderColor: 'var(--border-muted)',
                color: 'var(--text-primary)'
              }}
            />
            <button
              type="submit"
              disabled={loading || !inputValue.trim()}
              className="h-8 w-8 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white flex items-center justify-center cursor-pointer transition-colors disabled:opacity-30 shrink-0 shadow-md shadow-indigo-600/10"
            >
              <Send size={12} />
            </button>
          </form>
        </div>
      )}
    </>
  );
}
